# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

# Setup
title:            Better Together
tagline:          'Tab Church + Grace Bible Church'
description:      'Description Will Go Here'
url:              http://better-together.church
baseurl:          /

author:
  name:           'Lou Page'
  url:            https://twitter.com/loupage

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

videos:
  video_01:
    title:        'Video One'
    url:          https://www.youtube.com/watch?v=bRPQmaFQiwM
  video_02:
    title:        'Video Two'
    url:          https://www.youtube.com/watch?v=bRPQmaFQiwM

collections:
  faq_questions:
    output: true
